name: Lint
on: [push, pull_request]
jobs:
  build-advanced-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install JS Dependencies
      run: cd advanced-integration &&  npm install
    - name: Run ESLint
      run: cd advanced-integration &&  npm run lint
  
